postgresql:
  auth:
    postgresPassword: "Srt2022@"
    database: postgres
  
  global:
    security:
      allowInsecureImages: true

  image:
    repository: bitnamilegacy/postgresql

  primary:
    extendedConfiguration: |-
      shared_preload_libraries = 'pg_stat_statements'
      pg_stat_statements.max = 10000
      pg_stat_statements.track_utility = on
      pg_stat_statements.track = all
      track_io_timing = on
      max_connections = 500
      idle_in_transaction_session_timeout = 60000
      statement_timeout = 30000
      lock_timeout = 5000
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 1Gi
