apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oxii-hasura-subcription.fullname" . }}-config
data:
{{- if .Values.envConfigmap }}
{{- range $key, $value := .Values.envConfigmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
