jenkins:
  controller:
    admin:
      username: "admin"
      password: "Srt2022@"
      createSecret: true
    installPlugins: true
    JCasC:
      defaultConfig: true
    sidecars:
      configAutoReload:
        enabled: false

  persistence:
    storageClass: local-path
    size: 1Gi

  serviceAccount:
    create: true
    name: jenkins

  serviceAccountAgent:
    create: true
    name: jenkins-agent
