jenkins:
  controller:
    admin:
      username: "admin"
      password: "Srt2022@"
      createSecret: true
    installPlugins:
      - kubernetes:4423.vb_59f230b_ce53
      - workflow-aggregator:608.v67378e9d3db_1
      - git:5.10.1
      - configuration-as-code:2061.vc08919f7fc37
    JCasC:
      defaultConfig: true
    sidecars:
      configAutoReload:
        enabled: false

  persistence:
    storageClass: local-path
    size: 1Gi

  serviceAccount:
    create: true
    name: jenkins

  serviceAccountAgent:
    create: true
    name: jenkins-agent
