replicaCount: 1

image:
  repository: hasura/graphql-engine
  pullPolicy: IfNotPresent
  tag: "v2.46.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 8080
resources: {}
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 90 # Đã tăng
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 90 # Đã tăng
  timeoutSeconds: 5
  periodSeconds: 10
  failureThreshold: 3
  httpGet:
    path: /healthz
    port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
affinity: {}
tolerations: []

envConfigmap:
  HASURA_GRAPHQL_AUTH_HOOK: ""
  HASURA_GRAPHQL_AUTH_HOOK_MODE: "GET"
  HASURA_GRAPHQL_CORS_DOMAIN: "*"
  HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
  HASURA_GRAPHQL_ENABLE_PERSISTED_QUERIES: "true"
  HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"
  HASURA_GRAPHQL_ENABLE_RELAY: "true"
